output 'Hello World\n';
string name;
input name;
integer number = 5;
bool exampleBoolean = true;
output(number + 400);
func add(integer a, integer b);
while (exampleBoolean && (number == 5));
if (number >= 5);
else;
end;